name: Build LaTeX document
on:
  push:
    paths:
      - "**.tex"
      - "**.bib" # or any other file type that influences your LaTeX build

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Cache for LaTeX downloads
      - name: Cache LaTeX packages
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/share/texmf
            /usr/local/texlive
            /root/.texlive
            *.aux
            *.bbl
            *.blg
            *.acn
            *.acr
            *.alg
            *.bcf
            *.fdb_latexmk
            *.fls *.glg
            *.glo
            *.gls
            *.idx
            *.ilg
            *.ind
            *.ist
            *.loe
            *.maf
            *.mtc
            *.toc
            *.out
            *.run.xml
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "scinote.tex"
          glob_root_file: true
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          args: "-output-directory=."

      - name: Update README with the new PDF link
        run: |
          sed -i "s|https://github.com/cauliyang/learning_notes/blob/main/scinote-.*.pdf|https://github.com/cauliyang/learning_notes/blob/main/scinote-$TODAY.pdf|" README.md

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git commit -m "update pdf" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
