name: Build LaTeX document
on:
  push:
    paths:
      - "**.tex"
      - "**.bib" # or any other file type that influences your LaTeX build

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Cache for LaTeX downloads
      - name: Cache LaTeX packages
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/share/texmf
            /usr/local/texlive
            /root/.texlive
            *.aux
            *.bbl
            *.blg
            *.acn
            *.acr
            *.alg
            *.bcf
            *.fdb_latexmk
            *.fls *.glg
            *.glo
            *.gls
            *.idx
            *.ilg
            *.ind
            *.ist
            *.loe
            *.maf
            *.mtc
            *.toc
            *.out
            *.run.xml
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "scinote.tex"
          glob_root_file: true
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          args: "-output-directory=."

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: scinote.pdf
